# Generated by Django 5.0.4 on 2024-05-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='cake_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kart.cake'),
        ),
    ]
