# Generated by Django 5.0.4 on 2024-05-18 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0002_basketitem_cake_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='cakevariant_object',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='cakevariant_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kart.cakevariant'),
        ),
    ]
