# Generated by Django 5.0.4 on 2024-05-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0005_remove_basketitem_cakevariant_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='cake_object',
        ),
    ]
