# Generated by Django 5.0.4 on 2024-05-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0006_remove_basketitem_cake_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='size_object',
        ),
    ]
